//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollingLineSavegameFix.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RollingLineSavegameFix.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ct_dynamic,1,X_Y_Z,0_118.7188_0,11,-1,-1,0,0,0,0,0,0,0,0,0,0,0,-1,0,,1_0_17.8_10_7.54_1_-1.652195E-06_-6.437301E-06_-9.225045E-05_-0.06684428_0.05747461_0.7618518_356.1857_-1.611375E-08_0_4.748599_169.9722_0_7_0_0_0_0_180_0_0_6_22_1_1_12,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,,1,%ct_dynamic,1,X_Y_Z,8.69113_76.45975_348.0763,19,-1,-1,0,0,0,1,0,0,0,0,0,0,0,-1,1,,8_1_3_30_7.5_0_6_22_1_0.1_2,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,2&amp;kcc0:h7:s56:v78:lr50:hr0&amp;kcc0:h7:s56:v68:lr50:hr0&amp;kcc0:h7:s56:v68:lr50:hr0&amp;-1&amp;kcc0:h7:s36: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services_Move_MultipleTracks_ExpectedResult {
            get {
                return ResourceManager.GetString("Services_Move_MultipleTracks_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ct_dynamic,1,16.42576_2.081065_61.173,0_118.7188_0,11,-1,-1,0,0,0,0,0,0,0,0,0,0,0,-1,0,,1_0_17.8_10_7.54_1_-1.652195E-06_-6.437301E-06_-9.225045E-05_-0.06684428_0.05747461_0.7618518_356.1857_-1.611375E-08_0_4.748599_169.9722_0_7_0_0_0_0_180_0_0_6_22_1_1_12,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,,1,%ct_dynamic,1,16.88964_2.089037_62.57778,8.69113_76.45975_348.0763,19,-1,-1,0,0,0,1,0,0,0,0,0,0,0,-1,1,,8_1_3_30_7.5_0_6_22_1_0.1_2,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,2&amp;kcc0:h7:s56:v78:lr50:hr0&amp;kcc0:h7:s56:v68:lr50:hr0&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services_Move_MultipleTracks_Source {
            get {
                return ResourceManager.GetString("Services_Move_MultipleTracks_Source", resourceCulture);
            }
        }
    }
}
