//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollingLineSavegameFix.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RollingLineSavegameFix.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co_magazine_rack,1,X_Y_Z,0_299.2413_0,-1,1,0,0,0,0,,%2,co_bin,1,X_Y_Z,0_301.6713_0,-1,1,0,0,0,0,,%5,table_square_0,1,X_Y_Z,344.6943_340.7983_356.4974,-1,1,0,0,0,-1,,-1,kcc0:h0:s0:v49:lr50:hr20,0,,%20,Flaschbier_89974,1,X_Y_Z,10.64229_72.00494_348.4519,-1,1,0,0,0,0,,-1,kcc0:h25:s42:v37:lr50:hr20:mt1:ma50_kcc0:h57:s2:v96:lr50:hr20_kcc0:h1:s68:v77:lr50:hr20_kcc0:h11:s61:v78:lr50:hr20,0,,%7,co_shape_cube_0_snap,1,X_Y_Z,349.5707_341.6674_346.5048,-1,1,0,0,0,-1,,-1,kcc0:h0:s0:v74:lr50:hr20,0,,%8,co_pylon_new,1,X_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services_Move_MultipleObjects_ExpectedResult {
            get {
                return ResourceManager.GetString("Services_Move_MultipleObjects_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co_magazine_rack,1,4.8653_-0.2121_62.6697,0_299.2413_0,-1,1,0,0,0,0,,%2,co_bin,1,4.5317_-0.2121_61.2512,0_301.6713_0,-1,1,0,0,0,0,,%5,table_square_0,1,9.102201_-0.4459265_63.02061,344.6943_340.7983_356.4974,-1,1,0,0,0,-1,,-1,kcc0:h0:s0:v49:lr50:hr20,0,,%20,Flaschbier_89974,1,14.42129_1.918189_61.34037,10.64229_72.00494_348.4519,-1,1,0,0,0,0,,-1,kcc0:h25:s42:v37:lr50:hr20:mt1:ma50_kcc0:h57:s2:v96:lr50:hr20_kcc0:h1:s68:v77:lr50:hr20_kcc0:h11:s61:v78:lr50:hr20,0,,%7,co_shape_cube_0_snap,1,12.47174_1.918188_60. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services_Move_MultipleObjects_Source {
            get {
                return ResourceManager.GetString("Services_Move_MultipleObjects_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ct_dynamic,1,X_Y_Z,343.7986_331.1168_347.8066,22,-1,-1,0,0,0,0,0,0,0,0,0,0,0,-1,0,,1_1_11_14.4_7_0_6_22_1_1_12,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,,1,%ct_dynamic,1,X_Y_Z,359.7024_358.9953_346.6145,24,-1,-1,0,0,0,0,0,0,0,0,0,0,0,-1,0,,1_1_11_14.4_7_1_0_2.384186E-07_0_0.09742337_0.1195288_0.761869_351.0836_-2.653146E-08_0_8.634093_194.5687_0_7_0_0_0_0_180_0_0_6_22_1_1_12,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,,1,%ct_dynamic_flexy,1,X_Y_Z,19.37701_180.4953_15.23505,44,-1,-1,0,0,0,0,0,0,0,0,0,1,0.1062215_-0.08039427_- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services_Move_MultipleTracks_ExpectedResult {
            get {
                return ResourceManager.GetString("Services_Move_MultipleTracks_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ct_dynamic,1,9.210068_1.737302_61.45071,343.7986_331.1168_347.8066,22,-1,-1,0,0,0,0,0,0,0,0,0,0,0,-1,0,,1_1_11_14.4_7_0_6_22_1_1_12,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,,1,%ct_dynamic,1,8.844915_2.081676_62.90481,359.7024_358.9953_346.6145,24,-1,-1,0,0,0,0,0,0,0,0,0,0,0,-1,0,,1_1_11_14.4_7_1_0_2.384186E-07_0_0.09742337_0.1195288_0.761869_351.0836_-2.653146E-08_0_8.634093_194.5687_0_7_0_0_0_0_180_0_0_6_22_1_1_12,-1,0,7_0,kcc0:h0:s0:v49:lr50:hr20,,1,%ct_dynamic_flexy,1,8.73908_2.162071_62.16229,19.37701_180.4953 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services_Move_MultipleTracks_Source {
            get {
                return ResourceManager.GetString("Services_Move_MultipleTracks_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco_DSJ_bumblebee,1,0,0,0,X_Y_Z,0_138.9726_0,-1,-1,8,34,3,0.926,0,8,34,2,0.271,0,-1.15,1,1,0_0,,,,0,,,,,%6,QuickMod_NG Caboose 1,1,0,0,0,X_Y_Z,0_35.4941_0,-1,-1,8,41,0,0.825,0,8,40,3,0.155,0,0,0,0,,,,,0,,,,,%7,QuickMod_NG Box White 4 Mirror,1,0,0,0,X_Y_Z,0_248.6993_0,-1,-1,8,36,1,0.835,0,8,36,0,0.181,0,0,0,0,,,,,0,,,,,.
        /// </summary>
        internal static string Services_Move_MultipleWaggons_ExpectedResult {
            get {
                return ResourceManager.GetString("Services_Move_MultipleWaggons_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco_DSJ_bumblebee,1,0,0,0,13.8287_1.9288_61.4102,0_138.9726_0,-1,-1,8,34,3,0.926,0,8,34,2,0.271,0,-1.15,1,1,0_0,,,,0,,,,,%6,QuickMod_NG Caboose 1,1,0,0,0,16.6547_1.9288_61.2673,0_35.4941_0,-1,-1,8,41,0,0.825,0,8,40,3,0.155,0,0,0,0,,,,,0,,,,,%7,QuickMod_NG Box White 4 Mirror,1,0,0,0,17.2143_1.9288_60.2291,0_248.6993_0,-1,-1,8,36,1,0.835,0,8,36,0,0.181,0,0,0,0,,,,,0,,,,,.
        /// </summary>
        internal static string Services_Move_MultipleWaggons_Source {
            get {
                return ResourceManager.GetString("Services_Move_MultipleWaggons_Source", resourceCulture);
            }
        }
    }
}
